#######################################################
#|                                                   |#
#|  ,---.o               |              o|           |#
#|  `---..,---.,---..   .|    ,---.,---..|--- ,   .  |#
#|      |||   ||   ||   ||    ,---||    ||    |   |  |#
#|  `---'``   '`---|`---'`---'`---^`    ``---'`---|  |#
#|             `---'                          `---'  |#
#|                              Recode Version 17.3  |#
#######################################################

#_____________Checks_____________#
Movement:
  Fly:
    enabled: true
    setback: true
    max_vl: 10

  IrregularPositions:
    enabled: true
    setback: true
    max_vl: 15

  SpeedA:
    enabled: true
    setback: true
    max_vl: 15

  BoatFly:
    enabled: true
    setback: true
    max_vl: 8

ClientData:
  GroundSpoof:
    enabled: true
    damage: false
    setback: true
    max_vl: 6

Interactions:
  BadBlockPlace:
    enabled: true
    cancel: true
    max_vl: 5

  Packet:
    BadPacketsA:
      enabled: true
      cancel: true
      max_vl: 3
#_____________Settings_____________#
# Should flags be visible in the console?
console-log: true
# Kick when player reaches max_vl.
kick-enabled: false
# Displayed message when kicked for detection.
kick-message: "&8[&5âŒ›&8] &7Singularity cheat detection."









